"""create users and gear tables

Revision ID: 7bff32e2dd4c
Revises: 
Create Date: 2020-10-08 23:40:41.876431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bff32e2dd4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geartypes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('musicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=40), nullable=False),
    sa.Column('lastName', sa.String(length=40), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('mediaLink', sa.String(length=2000), nullable=True),
    sa.Column('hashed_password', sa.Binary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('is_required', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('gearTypeId', sa.Integer(), nullable=False),
    sa.Column('musicianId', sa.Integer(), nullable=False),
    sa.Column('mediaLink', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['gearTypeId'], ['geartypes.id'], ),
    sa.ForeignKeyConstraint(['musicianId'], ['musicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('geartypetags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gearTypeId', sa.Integer(), nullable=False),
    sa.Column('tagId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gearTypeId'], ['geartypes.id'], ),
    sa.ForeignKeyConstraint(['tagId'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gear_attribute',
    sa.Column('gearId', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=500), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['gearId'], ['gear.id'], ),
    sa.PrimaryKeyConstraint('gearId', 'tag')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gear_attribute')
    op.drop_table('geartypetags')
    op.drop_table('gear')
    op.drop_table('tags')
    op.drop_table('musicians')
    op.drop_table('geartypes')
    # ### end Alembic commands ###
